FROM python:3.12-slim

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 7000

CMD alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 7000
