networks:
  traefik:
    external: true
  monitoring:
    external: true
  enhanced-git-prod:
    external: true

name: enhanced-git-prod-back
services:
  db:
    container_name: prod-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${BDD_USER}
      POSTGRES_PASSWORD: ${BDD_PSWD}
      POSTGRES_DB: ${BDD_NAME}
    volumes:
      - db_volume_prod:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BDD_USER} -d ${BDD_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - enhanced-git-prod
      - monitoring
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "400"
        loki-retries: "5"
        loki-external-labels: "app=prod-db"
  api:
    restart: always
    container_name: prod-api
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    environment:
      BDD_USER: ${BDD_USER}
      BDD_PSWD: ${BDD_PSWD}
      BDD_HOST: ${BDD_HOST}
      BDD_PORT: ${BDD_PORT}
      BDD_NAME: ${BDD_NAME}
      BEARER_SECRET_TOKEN: ${ENCRYPT_TOKEN}
      REFRESH_SECRET_TOKEN: ${ENCRYPT_TOKEN}
      ENCRYPT_DATA: ${ENCRYPT_DATA}
      GITHUB_CLIENT: ${GITHUB_CLIENT}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      FRONT_URL: ${FRONT_URL}
    networks:
      - traefik
      - enhanced-git-prod
      - monitoring
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prod-api.rule=Host(`apiprod.enhanced-git.com`)"
      - "traefik.http.routers.prod-api.entrypoints=websecure"
      - "traefik.http.routers.prod-api.tls=true"
      - "traefik.http.routers.prod-api.tls.certresolver=cloudflare"
      - "traefik.http.services.prod-api.loadbalancer.server.port=7000"
      - "traefik.docker.network=traefik"

    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "400"
        loki-retries: "5"
        loki-external-labels: "app=prod-api"

volumes:
  db_volume_prod:
