version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  api:
    build:
      dockerfile: Dockerfile
      context: .  # Assure-toi d'avoir le bon contexte de build
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+pymysql://root:${ROOT_PASSWORD}@db:3306/enhanced_git_test"
    volumes:
      - .:/app  # Monte le dossier local de l’application
      - ./cert:/app/cert  # Monte le dossier des certificats pour SSL

volumes:
  db_volume:
