"""update_gitlab

Revision ID: ff7e8c18a4f4
Revises: 1fcc6eb12d78
Create Date: 2025-08-03 23:21:18.554629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7e8c18a4f4'
down_revision: Union[str, Sequence[str], None] = '1fcc6eb12d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Connection', sa.Column('refresh_token', sa.Text, nullable=True))
    op.alter_column('Connection', 'access_token', existing_type=sa.String(length=50), type_=sa.Text, existing_nullable=False)
    op.create_unique_constraint(None, 'Portfolio', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Portfolio', type_='unique')
    op.alter_column('Connection', 'access_token', existing_type=sa.Text, type_=sa.String(length=50), existing_nullable=True)
    op.drop_column('Connection', 'refresh_token')
    # ### end Alembic commands ###
